version: '3'

services:
  consulserver01:
    build:
      context: .docker
    image: joaocsv/consul
    container_name: consulserver01
    volumes:
      - ./servers/server-01/:/etc/consul.d
    networks:
      consul_cluster:
        ipv4_address: 172.18.0.3

  consulserver02:
    build:
      context: .docker
    image: joaocsv/consul
    container_name: consulserver02
    volumes:
      - ./servers/server-02/:/etc/consul.d
    networks:
      consul_cluster:
        ipv4_address: 172.18.0.2
    
  
  consulserver03:
    build:
      context: .docker
    image: joaocsv/consul
    container_name: consulserver03
    volumes:
      - ./servers/server-03/:/etc/consul.d
    networks:
      consul_cluster:
        ipv4_address: 172.18.0.5

  consulclient01:
    build:
      context: .docker
    image: joaocsv/consul
    container_name: consulclient01
    volumes:
      - ./clients/client-01/:/etc/consul.d
    networks:
      consul_cluster:
        ipv4_address: 172.18.0.6

  consulclient02:
    build:
      context: .docker
    image: joaocsv/consul
    container_name: consulclient02
    volumes:
      - ./clients/client-02/:/etc/consul.d
    networks:
      consul_cluster:
        ipv4_address: 172.18.0.4

networks:
  consul_cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24